name: build github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -name: Install Modules
        run: yarn install

      - name: Build
        run: yarn buildLinux
